### ISSUE TITLE
How did you deal with ethical concerns regarding collecting data from Instagram

### ISSUE THREAD

**Issue by kznlp** [wzhings/antivaccine_detection#1]
Hi Zuhui,
Thank you for sharing your work and the dataset. I am also a researcher who is interested in collecting and publishing some Instagram datasets for research purposes, but I have been kept telling that crawling data from Instagram is violating their [Terms of Service](https://www.instagram.com/about/legal/terms/before-january-19-2013/#:~:text=You%20may%20not%20use%20the,any%20illegal%20or%20unauthorized%20purpose.&text=You%20must%20not%20access%20Instagram's,to%20user%20profiles%20and%20photos.). I have checked many discussions online but I could not find a solid evidence to show that collecting Instagram data for research purposes is both legal and ethical. I wonder if you have found supporting evidence to show that crawling public available posts from Instagram and publish the dataset for research purpose is both legal and ethical? Really appreciate if you have any relevant experience. Thanks!

**Comment by wzhings** [comment]
Hi @kznlp, thank you for your interest in our paper. For data collection, it was reported in our manuscript. We also appreciate you opening this issue by creating a new GitHub account.
